[theme]
primaryColor="#4CAF50" # A shade of green
backgroundColor="#E8F5E9" # A lighter green/off-white
secondaryBackgroundColor="#A5D6A7" # Another green shade for sidebar/secondary elements
textColor="#212121"
font="sans serif"